Initial Commit
TheNewtonCapstone/blog pull request #35
Opened 2024-12-27 02:19 UTC by Shamiivan

This PR adds a new technical blog post about our experience using Micro-ROS in a Two-Wheeled Inverted Pendulum (TWIP) robot project. The post explores the challenges we faced with abstraction layers in real-time control systems and (MAYBE) provides insights for making architectural decisions.

2024-12-31 04:05 UTC, Rayan99k commented on _posts/2024-12-26-issues-with-microros.md
> +When we started working on our Two Wheel Inverted Pendulum (TWIP) project, I was determined to use ROS—mainly because it's a that counteless robotics videos swear by.
Proposed change: I was determined to use ROS—mainly because it's a system that countless robotics videos swear by.

2024-12-31 04:08 UTC, Rayan99k commented on _posts/2024-12-26-issues-with-microros.md
> +There’s a very interesting blog written by Joel Spolsky that highlights a key insight:
link to the blog?

2024-12-31 04:17 UTC, Rayan99k commented on _posts/2024-12-26-issues-with-microros.md
> +THAT IT!
THAT'S IT!

slam dunk

2024-12-31 04:52 UTC, Rayan99k approved these changes

2025-01-01 22:37 UTC, mbedair commented on _posts/2024-12-26-issues-with-microros.md
> +When we started working on our Two Wheel Inverted Pendulum (TWIP) project, I was determined to use ROS—mainly because it's a that counteless robotics videos swear by.
Agree with Rayan here.

2025-01-01 23:12 UTC, mbedair requested changes
Few grammatical errors, but a great read!

2025-01-01 23:12 UTC, mbedair commented on _posts/2024-12-26-issues-with-microros.md
> +This is a very good thing, because components can communicate using different programming languages, physical system and computational capacity.
Would change this to:
This is an excellent concept in theory since components can communicate using different programming languages, physical systems, and computational capacities.

2025-01-01 23:12 UTC, mbedair commented on _posts/2024-12-26-issues-with-microros.md
> +Timing is crucial.The system needs to know exactly when each measurement was taken and when each correction was applied
a missing period at the end of the sentence.

2025-01-01 23:12 UTC, mbedair commented on _posts/2024-12-26-issues-with-microros.md
> +Here’a simplified version of initial code. We initialize Wi-Fi transport, set up the publisher for IMU data, and subscribe to motor commands. The timer and executor ensure continuous data flow, trigg
Would change: "Here’a simplified version of initial code." to "Here's a simplified version of the initial code"

2025-01-01 23:12 UTC, mbedair commented on _posts/2024-12-26-issues-with-microros.md
> +Micro-ROS introduces Quality of Service (QoS) settings to manage message delivery and buffering. The History Depth option allows storing the last N (specified constant) messages. The
is this a hanging sentence? the way there are two lines after ". The"?

2025-01-01 23:12 UTC, mbedair commented on _posts/2024-12-26-issues-with-microros.md
> +A leaky abstraction occurs when high-level interface (microros in our case) fails to completely hide low-level implementation details, forcing you to understand the underlying complexity that it was
1- You type micro-ROS in two different formats, first and last line.
2- check the last line at "micro-ROS forced us to confront complex" What comes after complex?

2025-01-01 23:12 UTC, mbedair commented on _posts/2024-12-26-issues-with-microros.md
> +Some frameworks, are worth the investment because they solve a problem harder than.
Missing context: harder than....?

2025-01-01 23:12 UTC, mbedair commented on _posts/2024-12-26-issues-with-microros.md
> +For example, we stuck with ROS for our newton project because of the perception and planning aspect introduces camera, imu and sensor fusion that was easier to deal with ROS
Would change it to:
For example, we stuck with ROS for our Newton project because the perception and planning aspect introduces a camera, IMU, and sensor fusion making it simpler to deal with ROS.

2025-01-01 23:12 UTC, mbedair commented on _posts/2024-12-26-issues-with-microros.md
> +We have encoured a lot of annoyance with the framework but the problem solved is worth.
"worth the trouble."

2025-01-01 23:12 UTC, mbedair commented on _posts/2024-12-26-issues-with-microros.md
> +Here's the topic list
wheres the topic list?

2025-01-01 23:12 UTC, mbedair commented on _posts/2024-12-26-issues-with-microros.md
> +You may not know whe the complexity-benefit ratio is, but keep a mental note as you go.
"You may not know **_what_** the..."

2025-01-01 23:38 UTC, AugustDG requested changes
Awesome!

2025-01-01 23:38 UTC, AugustDG commented on _posts/2024-12-26-issues-with-microros.md
> +Since then, our relationship with the ROS ecosystem has been, to put it mildly, turbulent.There is much to cover about the subject. This blog explores a small part of the story, mainly, using Micro R
```suggestion
Since then, our relationship with the ROS ecosystem has been, to put it mildly, turbulent. There is much to cover about the subject. This blog explores a small part of the story, by mainly using micro-ROS. 
```

2025-01-01 23:38 UTC, AugustDG commented on _posts/2024-12-26-issues-with-microros.md
> +When we started working on our Two Wheel Inverted Pendulum (TWIP) project, I was determined to use ROS—mainly because it's a that counteless robotics videos swear by.
```suggestion
When we started working on our TWIP (Two Wheel Inverted Pendulum) project, I was determined to use ROS—mainly because it's a system that countless robotics videos swear by. 
```

2025-01-01 23:38 UTC, AugustDG commented on _posts/2024-12-26-issues-with-microros.md
> +This is a very good thing, because components can communicate using different programming languages, physical system and computational capacity.
```suggestion
This is an excellent concept in theory since components can communicate using different programming languages, physical systems, and computational capacities.
```

2025-01-01 23:38 UTC, AugustDG commented on _posts/2024-12-26-issues-with-microros.md
> +Timing is crucial.The system needs to know exactly when each measurement was taken and when each correction was applied
```suggestion
Timing is crucial. The system needs to know exactly when each measurement was taken and when each correction was applied.
```

2025-01-01 23:38 UTC, AugustDG commented on _posts/2024-12-26-issues-with-microros.md
> +date: 2024-11-29
```suggestion
date: 2024-12-26
```

2025-01-01 23:38 UTC, AugustDG commented on _posts/2024-12-26-issues-with-microros.md
> +1. The IMU timer callback fires at a fixed rate (1kHz in our case) and publishes the pendulum's angle on `/imu_data` topic
```suggestion
1. The IMU timer callback fires at a fixed rate (1kHz in our case) and publishes the pendulum's angle on the `/imu_data` topic
```

2025-01-01 23:38 UTC, AugustDG commented on _posts/2024-12-26-issues-with-microros.md
> +2. The control loop runs one iteration:
```suggestion
2. The control loop runs one iteration, by:
```

2025-01-01 23:38 UTC, AugustDG commented on _posts/2024-12-26-issues-with-microros.md
> +    - Publishes motor commands on the `motor_cmd` topic
```suggestion
    - Reading the current angle
    - Calculating required corrective torque
    - Publishing motor commands on the `motor_cmd` topic
```

2025-01-01 23:38 UTC, AugustDG commented on _posts/2024-12-26-issues-with-microros.md
> +6. The cycle repeats with fresh IMU data
```suggestion
3. The ESP32 subscribes to the `/motor_cmd` topic and triggers the callback when new data is received
4. The ESP32 outputs a PWM (Pulse Width Modulation) value which translates to output torque
5. The physical system responds
6. The cycle repeats with fresh IMU data
```

2025-01-01 23:38 UTC, AugustDG commented on _posts/2024-12-26-issues-with-microros.md
> +Microcontrollers like the ESP32 typically lack the computational power and memory to run a full ROS 2 node (remember Augusto’s point about this ?).
```suggestion
Microcontrollers like the ESP32 typically lack the computational power and memory to run a full ROS 2 node (remember Augusto’s point about this?).
```

2025-01-01 23:38 UTC, AugustDG commented on _posts/2024-12-26-issues-with-microros.md
> +Here’a simplified version of initial code. We initialize Wi-Fi transport, set up the publisher for IMU data, and subscribe to motor commands. The timer and executor ensure continuous data flow, trigg
```suggestion
Here's a simplified version of the initial code. We initialize Wi-Fi transport, set up the publisher for IMU data, and subscribe to motor commands. The timer and executor ensure continuous data flow, triggering the motor control loop based on incoming sensor readings.
```

2025-01-01 23:38 UTC, AugustDG commented on _posts/2024-12-26-issues-with-microros.md
> +  set_microros_wifi_transports("SSID", "PASSWORD", "192.XXX.X.XXX", 8888);
```suggestion
  set_microros_wifi_transports("SSID", "PASSWORD", "192.XXX.XXX.XXX", 8888);
```

2025-01-01 23:38 UTC, AugustDG commented on _posts/2024-12-26-issues-with-microros.md
> +There’s a very interesting blog written by Joel Spolsky that highlights a key insight:
```suggestion
There’s a very interesting [blog](https://www.joelonsoftware.com/2002/11/11/the-law-of-leaky-abstractions/) written by Joel Spolsky that highlights a key insight:
```

2025-01-01 23:38 UTC, AugustDG commented on _posts/2024-12-26-issues-with-microros.md
> +- Network congestion and the concept of batching
```suggestion
```

2025-01-01 23:38 UTC, AugustDG commented on _posts/2024-12-26-issues-with-microros.md
> +### The Role of micro-ROS and Micro-Ros Agent
```suggestion
### The Role of micro-ROS and micro-Ros Agent
```

2025-01-01 23:38 UTC, AugustDG commented on _posts/2024-12-26-issues-with-microros.md
> +For more details about micro-ros agent, you can refer to the [micro-ROS Agent GitHub repository](https://github.com/micro-ROS/micro-ROS-Agent).
```suggestion
For more details about micro-ROS agent, you can refer to the [micro-ROS Agent GitHub repository](https://github.com/micro-ROS/micro-ROS-Agent).
```

2025-01-01 23:38 UTC, AugustDG commented on _posts/2024-12-26-issues-with-microros.md
> +Additionally, Network Congestion Batching helps reduce overhead by batching messages during network congestion, improving communication efficiency.
```suggestion
Additionally, NBC (Network Congestion Batching) helps reduce overhead by batching messages during network congestion, improving communication efficiency.
```

2025-01-01 23:38 UTC, AugustDG commented on _posts/2024-12-26-issues-with-microros.md
> +1. The IMU timercallback fires at a fixed rate (1kHz) and publishes the pendulum's angle
```suggestion
1. The IMU timer callback fires at a fixed rate (1kHz) and publishes the pendulum's angle
```

2025-01-01 23:38 UTC, AugustDG commented on _posts/2024-12-26-issues-with-microros.md
> +2. Initial motor command triggers with a 5ms set_torque() delay
```suggestion
2. An initial motor command triggers with a 5ms set_torque() delay
```

2025-01-01 23:38 UTC, AugustDG commented on _posts/2024-12-26-issues-with-microros.md
> +    - Each command based on increasingly stale data, thus responding to outdated pendulum positions
Love this sentence!

2025-01-01 23:38 UTC, AugustDG commented on _posts/2024-12-26-issues-with-microros.md
> +6. Next blocking delay occurs, repeating the cycle
```suggestion
6. Next blocking delay occurs, repeating the cycle and accelerating the positive feedback loop
```

2025-01-01 23:38 UTC, AugustDG commented on _posts/2024-12-26-issues-with-microros.md
> +A leaky abstraction occurs when high-level interface (microros in our case) fails to completely hide low-level implementation details, forcing you to understand the underlying complexity that it was
```suggestion
A leaky abstraction occurs when high-level interface (micro-ROS in our case) fails to completely hide low-level implementation details, forcing you to understand the underlying complexity that it was trying to hide. My initial reasoning was that we should avoid communication and use an abstraction. However, the "simple" abstraction provided by micro-ROS forced us to confront complex topics, including:
```

2025-01-01 23:38 UTC, AugustDG commented on _posts/2024-12-26-issues-with-microros.md
> +In hindsight, there is a couple of solutions we could have implemented, but we did not understand the system at the time.
```suggestion
In hindsight, there is a couple of solutions we could have implemented, but not knowing the system well, we simply overlooked.
```

2025-01-01 23:38 UTC, AugustDG commented on _posts/2024-12-26-issues-with-microros.md
> +THAT IT!
```suggestion
**THAT'S IT!**
```

2025-01-01 23:38 UTC, AugustDG commented on _posts/2024-12-26-issues-with-microros.md
> +Here's the paradox of abstractions that Joel Spolsky points out in his blog:
```suggestion
In Spolsky's [blog](https://www.joelonsoftware.com/2002/11/11/the-law-of-leaky-abstractions/), he points out: 
```

2025-01-01 23:38 UTC, AugustDG commented on _posts/2024-12-26-issues-with-microros.md
> +However, here’s a framework that may guide your decision making, not just for micro-ROS, but for any tool:
```suggestion
However, here’s a framework that may guide your decision making for any tool, not just for micro-ROS:
```

2025-01-01 23:38 UTC, AugustDG commented on _posts/2024-12-26-issues-with-microros.md
> + - What's the complexity-benefit ratio
```suggestion
 - What's the complexity-benefit ratio?
```

2025-01-01 23:38 UTC, AugustDG commented on _posts/2024-12-26-issues-with-microros.md
> +Some frameworks, are worth the investment because they solve a problem harder than.
```suggestion
Some frameworks are worth the investment because they solve a bigger, harder, overall problem. 
```

2025-01-01 23:38 UTC, AugustDG commented on _posts/2024-12-26-issues-with-microros.md
> +For example, we stuck with ROS for our newton project because of the perception and planning aspect introduces camera, imu and sensor fusion that was easier to deal with ROS
```suggestion
For example, we stuck with ROS for our Newton project because the perception and planning aspect introduces a camera, IMU, and sensor fusion making it simpler to deal with ROS.
```

2025-01-01 23:38 UTC, AugustDG commented on _posts/2024-12-26-issues-with-microros.md
> +Here's the topic list
```suggestion
```

2025-01-01 23:38 UTC, AugustDG commented on _posts/2024-12-26-issues-with-microros.md
> +We have encoured a lot of annoyance with the framework but the problem solved is worth.
```suggestion
We have encountered a lot of annoyances with ROS but the overall problem that it solves is worth the trouble. 
```

2025-01-01 23:38 UTC, AugustDG commented on _posts/2024-12-26-issues-with-microros.md
> +However, for other projects, like our TWIP controller, the learning investment might outweigh the benefits.
```suggestion
That being said, for other projects, like TWIP, the learning investment might have outweighed the benefits.
```

2025-01-01 23:38 UTC, AugustDG commented on _posts/2024-12-26-issues-with-microros.md
> +You may not know whe the complexity-benefit ratio is, but keep a mental note as you go.
```suggestion
You may not know what the complexity-benefit ratio is, but keep it in mind as you go through exploring the technology. 
```

2025-01-01 23:38 UTC, AugustDG commented on _posts/2024-12-26-issues-with-microros.md
> +In the world of software, they're not a matter of if, but when. Sometimes, as we learned, the simplest solution might be the most robust one.
```suggestion
In the world of software, they're not a matter of if, but when. Sometimes, as we learned, the simplest solution might be the most robust one. Or it might be too robust, but requires heavy investment in learning it.
```

2025-01-09 07:17 UTC, merged